import {  FaShoppingCart} from "react-icons/fa";
export const FeaturedItems=[
    {
        Company:'IndianGarrageCo',
        Itemname:'BlackShirt',
        url:"/images/MensPageImg/blackShirt.png",
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'BlackShirt',
        url:'/images/MensPageImg/OsGrey.png',
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'BlackShirt',
        url:'/images/MensPageImg/Cargo1.png',
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'BlackShirt',
        url:'/images/MensPageImg/floralshirt.png',
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'BlackShirt',
        url:'/images/MensPageImg/shoes1.png',
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'BlackShirt',
        url:'/images/MensPageImg/Short1.png',
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'BlackShirt',
        url:'/images/MensPageImg/Track4.png',
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'BlackShirt',
        url:'/images/MensPageImg/flop1.png',
        price:'50$',
        cart:<FaShoppingCart/>
    }
]