import {  FaShoppingCart} from "react-icons/fa";
export const WomenAssets=[
    {
        Company:'IndianGarrageCo',
        Itemname:'Jacket',
        url:"/images/WomenAssets/Wjacket1.png",
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'Jacket',
        url:"/images/WomenAssets/Wjacket2.png",
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'Jacket',
        url:"/images/WomenAssets/Wjacket3.png",
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'Jacket',
        url:"/images/WomenAssets/Wjeans1.png",
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'Jacket',
        url:"/images/WomenAssets/Wjeans2.png",
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'Jacket',
        url:"/images/WomenAssets/Wjeans3.png",
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'Jacket',
        url:"/images/WomenAssets/Wplazo1.png",
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'Jacket',
        url:"/images/WomenAssets/Wplazo2.png",
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'Jacket',
        url:"/images/WomenAssets/Wplazo3.png",
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'Jacket',
        url:"/images/WomenAssets/Wskirt1.png",
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'Jacket',
        url:"/images/WomenAssets/Wskirt2.png",
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'Jacket',
        url:"/images/WomenAssets/Wskirt3.png",
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'Jacket',
        url:"/images/WomenAssets/WTop1.png",
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'Jacket',
        url:"/images/WomenAssets/Wtop2.png",
        price:'50$',
        cart:<FaShoppingCart/>
    },
    {
        Company:'IndianGarrageCo',
        Itemname:'Jacket',
        url:"/images/WomenAssets/Wtop3.png",
        price:'50$',
        cart:<FaShoppingCart/>
    }
]